### ISSUE TITLE
Implement Bootstrap

### ISSUE THREAD

**Issue by smcunning** [TuringGameNight/Front-End#28]
This is a really large project actually 😅

Pages to style in the `bootstrap_setup` branch:
- [x] Game Night New Page
- [x] Game Night Show Page
- [x] Games/Search Index Page for results
- [x] Games/Search New Page
- [x] Home Index Page
- [x] Dashboard
- [x] Game New Page

**Comment by helloeduardo** [comment]
Hitting a blocker until the oauth implementation branch is merged into main and api calls can be successfully made between the front and back-end. 

At the moment the `bootstrap_setup` branch cannot access all pages in development without encountering numerous errors, thus we cannot visually style.

**Comment by helloeduardo** [comment]
Made some progress with the latest changes to main. All views should have some basic styling now in the `bootstrap_setup` branch
