### ISSUE TITLE
FE should pass all data about a game when adding game to shelf

### ISSUE THREAD

**Issue by katemorris** [TuringGameNight/Front-End#32]
Regardless of if it is a manually added game or one from search results, all data should be passed back to the BE so they can add that game to the DB.

Right now it is just the "game id" which won't be present in the same format every time. A new manually added game won't have one from our DB or BGAtlas. The BG Atlas number won't be present in all games in our DB, so all searches will need to be done on name, alas.

**Comment by helloeduardo** [comment]
This issue has been resolved in a prior PR but was not linked. Closing.
