### ISSUE TITLE
Refactor Bootstrap

### ISSUE THREAD

**Issue by GarrettCottrell** [TuringGameNight/Front-End#41]
- [x] Style flash Messages
- [x] Logo redirect to home-page
- [x] Logout should redirect to /logout
- [x] Pull in user image
- [x] Make all buttons uniform
- [x] Make all cards grey uniform
- [x] Edit css file
- [x] Remove "Create a Game" from navbar

**Comment by GarrettCottrell** [comment]
Logout now redirects to /logout (Just confirming that the path is still being worked on)

**Comment by katemorris** [comment]
It is! I've got it in my branch, just got sidetracked with some personal stuff tonight.

**Comment by GarrettCottrell** [comment]
Awesome - thanks Kate!

**Comment by GarrettCottrell** [comment]
Adding profile image caused tests to fail due to the image not being in asset pipeline. Resolved by creating method to mock asset pipeline responses for test environment.

All issues discussed today have been implemented. Added some styling issues that I'll address tomorrow, as well as cleaning up the css file.
