### ISSUE TITLE
Bugs- see full details

### ISSUE THREAD

**Issue by ShaunDaneJames** [TuringGameNight/Front-End#42]
- [x] Cannot add game from search results if game doesn't have a duration
- [ ] Searching for game `#$%` doesn't yield error for user
- [x] You can a game more than once on your self
- [x] Game Nights are added despite error stating otherwise
- [x] Cannot create games
- [x] - Dashboard shows login button even if already logged in

## Other considerations ## 
- Should you be able add two game nights on the same night?
- If I am a visitor I don't understand why your links don't work, looks like your site is broken.
- Do we want a start time on a gamenight? 
- Should my list of games be sorted?
- If I have over 30 board games, can I search for one?

**Comment by ShaunDaneJames** [comment]
https://user-images.githubusercontent.com/58994078/104534801-33791b00-55d2-11eb-94ec-1c7d0a265411.mov

**Comment by ShaunDaneJames** [comment]
Searching for game #$% doesn't yield error for user


https://user-images.githubusercontent.com/58994078/104535672-ded69f80-55d3-11eb-8b10-0f7b0cc9a334.mov

**Comment by ShaunDaneJames** [comment]
You can a game more than once on your self


https://user-images.githubusercontent.com/58994078/104536333-227dd900-55d5-11eb-93e3-b16e55c0a856.mov

**Comment by ShaunDaneJames** [comment]
Game Nights are added despite error stating otherwise


https://user-images.githubusercontent.com/58994078/104538044-5c9caa00-55d8-11eb-9cc9-3b263beb5f6e.mov

**Comment by ShaunDaneJames** [comment]
Cannot create games

https://user-images.githubusercontent.com/58994078/104539589-19900600-55db-11eb-9e59-e17ec9e7226a.mov

**Comment by katemorris** [comment]
search for &*^ breaks the params as it is sent in the URI - I am not sure how to fix that one :(
